In [2]:
import pandas as pd
import numpy as np

In [58]:
#category = 'model driver data'
#fn = 'NLDAS_time[0.377900]_x[397]_y[136].csv'
#fn = 'NLDAS_time[0.377900]_x[401]_y[136].csv'
#fn = 'reservoir_io_obs.csv'
#fn = 'reservoir_io_sntemp.csv'

category = 'model predictions'
#fn = 'reservoir_downstream_preds.csv'
fn = 'paired_predicted_observed_temperatures.csv'
#fn = 'dwallin_stream_preds.csv'

table_loc = os.path.join('.', 'data', category, fn) 
df = pd.read_csv(table_loc)
print(len(df))
df.head(10)

33600

,seg_id_nat,issue_time,time,model_name,max_temp_c_predicted,max_temp_l90,max_temp_u90,prob_exceed_75,lead_time,max_temp_c,site_name,scenario
0,1450,2021-04-16,2021-04-16,DA,8.47,7.24,9.74,0.0,0,8.4,EBDR @ Harvard,+0cfs
1,1450,2021-04-16,2021-04-16,no_DA,8.45,7.31,9.62,0.0,0,8.4,EBDR @ Harvard,+0cfs
2,1450,2021-04-16,2021-04-17,DA,8.05,7.05,9.09,0.0,1,7.6,EBDR @ Harvard,+0cfs
3,1450,2021-04-16,2021-04-17,no_DA,8.04,7.06,9.08,0.0,1,7.6,EBDR @ Harvard,+0cfs
4,1450,2021-04-16,2021-04-18,DA,8.54,7.33,9.83,0.0,2,9.0,EBDR @ Harvard,+0cfs
5,1450,2021-04-16,2021-04-18,no_DA,8.53,7.31,9.85,0.0,2,9.0,EBDR @ Harvard,+0cfs
6,1450,2021-04-16,2021-04-19,DA,9.51,8.03,10.99,0.0,3,10.2,EBDR @ Harvard,+0cfs
7,1450,2021-04-16,2021-04-19,no_DA,9.51,8.03,11.02,0.0,3,10.2,EBDR @ Harvard,+0cfs
8,1450,2021-04-16,2021-04-20,DA,10.59,8.74,12.48,0.0,4,10.9,EBDR @ Harvard,+0cfs
9,1450,2021-04-16,2021-04-20,no_DA,10.60,8.77,12.56,0.0,4,10.9,EBDR @ Harvard,+0cfs

In [59]:
# check leap years
#leap years: 2020, 2016, 2012, 
#date_col = 'time'
#df[pd.to_datetime(df[date_col]).dt.year ==2016].iloc[59:61]

In [61]:
#len(df)
#df.replace([np.inf, -np.inf], np.nan).max().max()
#df.min().min()
df.sort_values('time')

,seg_id_nat,issue_time,time,model_name,max_temp_c_predicted,max_temp_l90,max_temp_u90,prob_exceed_75,lead_time,max_temp_c,site_name,scenario
0,1450,2021-04-16,2021-04-16,DA,8.47,7.24,9.74,0.0,0,8.4,EBDR @ Harvard,+0cfs
30913,1641,2021-04-16,2021-04-16,no_DA,9.74,8.61,10.86,0.0,0,NaN,NaN,+100cfs
30912,1641,2021-04-16,2021-04-16,DA,9.62,8.41,10.79,0.0,0,NaN,NaN,+100cfs
5376,1571,2021-04-16,2021-04-16,DA,8.23,6.94,9.46,0.0,0,7.8,WBDR @ Hancock,+0cfs
5377,1571,2021-04-16,2021-04-16,no_DA,8.02,6.80,9.17,0.0,0,7.8,WBDR @ Hancock,+0cfs
...,...,...,...,...,...,...,...,...,...,...,...,...
16127,1565,2021-09-30,2021-10-07,persistence,13.60,NaN,NaN,NaN,7,NaN,WBDR @ Hale Eddy,+0cfs
33598,1641,2021-09-30,2021-10-07,DA,14.84,13.25,16.10,0.0,7,NaN,NaN,+100cfs
17471,1571,2021-09-30,2021-10-07,persistence,15.40,NaN,NaN,NaN,7,NaN,WBDR @ Hancock,+0cfs
22846,1450,2021-09-30,2021-10-07,DA,11.61,10.13,12.79,0.0,7,NaN,NaN,+100cfs
33599,1641,2021-09-30,2021-10-07,no_DA,14.78,13.15,16.04,0.0,7,NaN,NaN,+100cfs

In [20]:
display(df.dtypes)

time          object
ShortWave    float64
LongWave     float64
AirTemp      float64
RelHum       float64
WindSpeed    float64
Rain         float64
Snow         float64
dtype: object

In [57]:
#df.sort_values('date')
len(df[df['dwallin_temp_c']>35])

4

In [67]:
col = 'model_name'

def check_whitespace(df, col):
    unique_vals = df[col].unique()
    for st in unique_vals:
        if st==None:
            continue
        print(st)
        if st.startswith(' '):
            print(f'    bad string ({st})')
        if st.endswith(' '):
            print(f'    bad string ({st})')   

def calc_metrics(df, col):
    print(f'    min: {df[col].min()}')
    print(f'    mean: {df[col].mean()}')
    print(f'    max: {df[col].max()}')

# Data do not have leading/trailing spaces or tabs.
print(f'checking column {col}')
# if type is string, check for whitespace
if df.dtypes[col]=='O':
    print(f'unique values: {df[col].unique()}')
    check_whitespace(df, col)
# if type is float, check min, max, mean
elif df.dtypes[col]=='float64':
    calc_metrics(df, col)

checking column model_name
unique values: ['DA' 'no_DA' 'persistence']
DA
no_DA
persistence